#pragma once
#include <iostream>
#include <chrono>
#include <cmath>
#include <vector>
#include <string>
#include <stdlib.h>
#include <algorithm>
#include <functional>
#include <sstream>
#include <map>
#include <memory>
#include <type_traits>
#include <fstream>
#include <stdio.h>
// All flags
#define CODEGEN
// All custom headers
#include "pNMPC.hpp"
#include "Database.hpp"
#include "Element.hpp"
#include "HyperStates.hpp"
#include "States.hpp"
#include "Inputs.hpp"
#include "Params.hpp"
#include "External.hpp"
#include "EquationProcessor.hpp"
#include "Builder.hpp"
#include "DiffEquation.hpp"
#include "ScalarConstraint.hpp"
#include "ScalarObjective.hpp"
#include "ParameterizationMap.hpp"
#include "BlockConstraint.hpp"
#include "ControlParamZ.hpp"
#include "Linear.hpp"
#include "Piecewise.hpp"
#include "SQPSolverCodeGen.hpp"
#include "PNMPCGEN.hpp"
